# permissions for end users to view volumereplicationrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumereplicationrequest-viewer-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumereplicationrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumereplicationrequests/status
  verbs:
  - get
