# permissions for end users to edit volumereplicationrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumereplicationrequest-editor-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumereplicationrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumereplicationrequests/status
  verbs:
  - get
